=== noffz-mbokcic/PR002165_FCT_NGPMH/UTP/LabView/MES/ResponseSupportData.xsd
<xs:schema attributeFormDefault="unqualified" elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="Body">
      <xs:complexType>
      <xs:sequence>
		  <xs:element name="ExecuteResponse">
			<xs:complexType>
			  <xs:sequence>
				<xs:element name="ExecuteResult">
				  <xs:complexType>
					<xs:sequence>
					  <xs:element type="xs:string" name="Result"/>
					  <xs:element type="xs:string" name="MessageCode"/>
					  <xs:element type="xs:string" name="MessageDescription"/>
					  <xs:element type="xs:string" name="BoxNo"/>
					  <xs:element type="xs:string" name="PalletNo"/>
					  <xs:element type="xs:string" name="PackingInstruction1"/>
					  <xs:element type="xs:string" name="PackingInstruction2"/>
					  <xs:element type="xs:string" name="PackingInstruction3"/>
					  <xs:element type="xs:string" name="PackingInstruction4"/>
					  <xs:element type="xs:string" name="PackingInstruction5"/>
					  <xs:element type="xs:string" name="SerialCount"/>
					  <xs:element type="xs:string" name="MaxSerialCount"/>
					  <xs:element type="xs:string" name="BoxCount"/>
					  <xs:element type="xs:string" name="MaxBoxCount"/>
					</xs:sequence>
				  </xs:complexType>
				</xs:element>
			  </xs:sequence>
			</xs:complexType>
		  </xs:element>
        </xs:sequence>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== noffz-mbokcic/PR002165_FCT_NGPMH/UTP/LabView/MES/CurrentResponse.xml
<?xml version="1.0" encoding="utf-8"?>
<Body xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	  xsi:noNamespaceSchemaLocation='ResponseSupportData.xsd'>
    <ExecuteResponse>
	 <ExecuteResult>
        <Result>string</Result>
        <MessageCode>string</MessageCode>
        <MessageDescription>string</MessageDescription>
        <BoxNo>string</BoxNo>
        <PalletNo>string</PalletNo>
        <PackingInstruction1>string1</PackingInstruction1>
        <PackingInstruction2>string2</PackingInstruction2>
        <PackingInstruction3>string3</PackingInstruction3>
        <PackingInstruction4>string4</PackingInstruction4>
        <PackingInstruction5>string</PackingInstruction5>
        <SerialCount>int</SerialCount>
        <MaxSerialCount>int</MaxSerialCount>
        <BoxCount>int</BoxCount>
        <MaxBoxCount>int</MaxBoxCount>
      </ExecuteResult>
	</ExecuteResponse>
</Body>
